[mypy]
explicit_package_bases = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-fastapi.*]
ignore_missing_imports = True

[mypy-uvicorn.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True