FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

FROM busybox:1.37
RUN adduser -D static
USER static
WORKDIR /home/static
COPY --from=builder /app/dist .
CMD ["busybox", "httpd", "-f", "-v", "-p", "5173"]