-- 実測スコアテーブル
CREATE TABLE IF NOT EXISTS actual_score (
    id SERIAL PRIMARY KEY,
    score INTEGER NOT NULL,
    place_id INTEGER NOT NULL REFERENCES place(id) ON DELETE CASCADE,
    target_datetime TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);