-- センサーテーブル
CREATE TABLE IF NOT EXISTS sensor (
    id SERIAL PRIMARY KEY,
    place_id INTEGER NOT NULL REFERENCES place(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);