-- 天候テーブル
CREATE TABLE IF NOT EXISTS weather (
    id SERIAL PRIMARY KEY,
    datetime TIMESTAMP NOT NULL,
    weather VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);